### ISSUE TITLE
Is AGPL the correct licensing

### ISSUE THREAD

**Issue by screeley44** [backube/scribe#130]
Clayton mentioned that no one should be using AGPL at Red Hat

**Comment by JohnStrunk** [comment]
AGPLv3 is on the [list of preferred licenses at Red Hat](https://source.redhat.com/groups/public/license-preference-guidelines/new_wiki/license_selection_guidelines).

The `api/*` files are also available via Apache v2 to ensure others can interface with Scribe programatically without their code being subject to copyleft.

**Comment by guymguym** [comment]
We discussed this before. IMHO AGPL is not adding any meaningful value to open source projects over apache license since the copyleft requirement is only pushing back on users that might be contrtibuting issues and discussions but cannot share back their code changes. I personally think that it's enough to get that engagement from users, even if their org does not allow them to contribute back their modifications/enhancements to the code.
